create table if not exists public.users (
    id_user bigint generated by default as identity primary key,
    nama_lengkap text not null,
    username text not null unique,
    password text not null,
    role text not null default 'user',
    status text not null default 'aktif',
    created_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
    id_item bigint generated by default as identity primary key,
    kategori text not null check (kategori in ('reagen', 'bmhp')),
    item text not null,
    stock_in_hand integer not null default 0,
    expire_date date not null,
    distributor text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.inventory_item_details (
    id_detail bigint generated by default as identity primary key,
    id_item bigint not null references public.inventory_items(id_item) on delete cascade,
    tanggal date not null,
    jumlah_masuk integer not null default 0 check (jumlah_masuk >= 0),
    nomor_batch text not null,
    expire_date date not null,
    satuan text not null,
    jumlah_keluar integer not null default 0 check (jumlah_keluar >= 0),
    distributor text not null,
    created_at timestamptz not null default now()
);

create or replace function public.refresh_item_stock(item_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.inventory_items
    set stock_in_hand = coalesce((
        select sum(jumlah_masuk - jumlah_keluar)
        from public.inventory_item_details
        where id_item = item_id
    ), 0)
    where id_item = item_id;
end;
$$;

create or replace function public.refresh_item_stock_from_detail()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    affected_item_id bigint;
begin
    affected_item_id := coalesce(new.id_item, old.id_item);
    perform public.refresh_item_stock(affected_item_id);

    if tg_op = 'UPDATE' and old.id_item is distinct from new.id_item then
        perform public.refresh_item_stock(old.id_item);
    end if;

    return coalesce(new, old);
end;
$$;

drop trigger if exists inventory_detail_refresh_stock on public.inventory_item_details;
create trigger inventory_detail_refresh_stock
after insert or update or delete on public.inventory_item_details
for each row execute function public.refresh_item_stock_from_detail();

insert into public.users (id_user, nama_lengkap, username, password, role, status)
values
    (1, 'Administrator Lab', 'admin', 'admin123', 'admin', 'aktif'),
    (2, 'CPNS Labkes 2026', 'CPNSLabkes2026', 'CPNSLabkes2026', 'user', 'aktif')
on conflict (username) do update set
    nama_lengkap = excluded.nama_lengkap,
    password = excluded.password,
    role = excluded.role,
    status = excluded.status;

select setval(pg_get_serial_sequence('public.users', 'id_user'), coalesce((select max(id_user) from public.users), 1), true);
select setval(pg_get_serial_sequence('public.inventory_items', 'id_item'), coalesce((select max(id_item) from public.inventory_items), 1), true);
select setval(pg_get_serial_sequence('public.inventory_item_details', 'id_detail'), coalesce((select max(id_detail) from public.inventory_item_details), 1), true);

alter table public.users enable row level security;
alter table public.inventory_items enable row level security;
alter table public.inventory_item_details enable row level security;

drop policy if exists "public users read" on public.users;
create policy "public users read"
on public.users for select
to anon
using (true);

drop policy if exists "public inventory items read" on public.inventory_items;
create policy "public inventory items read"
on public.inventory_items for select
to anon
using (true);

drop policy if exists "public inventory items insert" on public.inventory_items;
create policy "public inventory items insert"
on public.inventory_items for insert
to anon
with check (true);

drop policy if exists "public inventory items update" on public.inventory_items;
create policy "public inventory items update"
on public.inventory_items for update
to anon
using (true)
with check (true);

drop policy if exists "public inventory items delete" on public.inventory_items;
create policy "public inventory items delete"
on public.inventory_items for delete
to anon
using (true);

drop policy if exists "public inventory details read" on public.inventory_item_details;
create policy "public inventory details read"
on public.inventory_item_details for select
to anon
using (true);

drop policy if exists "public inventory details insert" on public.inventory_item_details;
create policy "public inventory details insert"
on public.inventory_item_details for insert
to anon
with check (true);

drop policy if exists "public inventory details update" on public.inventory_item_details;
create policy "public inventory details update"
on public.inventory_item_details for update
to anon
using (true)
with check (true);

drop policy if exists "public inventory details delete" on public.inventory_item_details;
create policy "public inventory details delete"
on public.inventory_item_details for delete
to anon
using (true);

grant usage on schema public to anon;
grant select on public.users to anon;
grant select, insert, update, delete on public.inventory_items to anon;
grant select, insert, update, delete on public.inventory_item_details to anon;
grant usage, select on all sequences in schema public to anon;
grant execute on function public.refresh_item_stock(bigint) to anon;
